#!/usr/bin/env python3
"""
extract_principles.py
Scans raw source files for principle keywords (content-hash dedup)
and writes structured extraction records for human review.
Never modifies Master System.
"""
import os, json, hashlib
from datetime import datetime

RAW = "raw_sources"
OUTPUT = "knowledge/extracted_principles_pending.json"
STATE = ".automation_state/extraction_state.json"

PRINCIPLE_KEYWORDS = [
    "barbell", "position sizing", "200dma", "200 dma", "covered call",
    "cash-secured put", "cash secured put", "naked option", "real return",
    "INR depreciation", "inr depreciation", "earnings growth", "EPS",
    "global liquidity", "dry powder", "diversif", "valuation",
    "20-40% correction", "portfolio weight", "parabolic", "moat",
    "k-shaped", "barbell portfolio", "20 stocks", "structural damage",
    "v-shaped", "operating leverage", "margin expansion", "agentic ai",
    "quantum", "moonshot", "king solomon", "short duration", "hard asset"
]

def load_state():
    os.makedirs(".automation_state", exist_ok=True)
    return json.load(open(STATE)) if os.path.exists(STATE) else {}

def save_state(s):
    json.dump(s, open(STATE, "w"), indent=2)

def content_hash(filepath):
    """
    # ⚠️ DDD GATE: Non-trivial write operation.
    # Before modifying this function's logic, follow Doubt-Driven Development:
    # 1. Write a CLAIM: what this function guarantees
    # 2. Extract the smallest reviewable artifact (this function's diff)
    # 3. Invoke adversarial review: "Find what is WRONG with this. Assume overconfidence."
    # 4. Log the decision in docs/ddd-decision-log.md
    # CONTRACT: Must return a unique SHA-256 hash of the file content to prevent duplicate extraction and source inflation.
    """
    with open(filepath, "rb") as f:
        return hashlib.sha256(f.read()).hexdigest()

def is_ai_generated(filepath):
    """
    # ⚠️ DDD GATE: Non-trivial write operation.
    # Before modifying this function's logic, follow Doubt-Driven Development:
    # 1. Write a CLAIM: what this function guarantees
    # 2. Extract the smallest reviewable artifact (this function's diff)
    # 3. Invoke adversarial review: "Find what is WRONG with this. Assume overconfidence."
    # 4. Log the decision in docs/ddd-decision-log.md
    # CONTRACT: Must correctly identify AI-generated markers to prevent AI content from being ingested as a primary source.
    """
    try:
        with open(filepath, encoding="utf-8", errors="ignore") as f:
            head = f.read(500).lower()
        ai_markers = ["ai-generated", "auto-generated", "gpt", "claude", "gemini",
                      "chatgpt", "summary by ai", "generated by"]
        return any(m in head for m in ai_markers)
    except Exception:
        return False

def extract_from_file(filepath):
    hits = []
    try:
        with open(filepath, encoding="utf-8", errors="ignore") as f:
            text = f.read().lower()
        for kw in PRINCIPLE_KEYWORDS:
            if kw.lower() in text:
                hits.append(kw)
    except Exception as e:
        print(f"  [extract] Error reading {filepath}: {e}")
    return hits

def main():
    """
    # ⚠️ DDD GATE: Non-trivial write operation.
    # Before modifying this function's logic, follow Doubt-Driven Development:
    # 1. Write a CLAIM: what this function guarantees
    # 2. Extract the smallest reviewable artifact (this function's diff)
    # 3. Invoke adversarial review: "Find what is WRONG with this. Assume overconfidence."
    # 4. Log the decision in docs/ddd-decision-log.md
    # CONTRACT: Must only write new, non-AI, unique extraction records to knowledge/extracted_principles_pending.json.
    """
    state = load_state()  # keyed by content hash
    results = []

    for root, _, files in os.walk(RAW):
        for fname in files:
            if fname.startswith("."):
                continue
            fpath = os.path.join(root, fname)
            chash = content_hash(fpath)

            if chash in state:
                continue  # already extracted — content-level dedup

            if is_ai_generated(fpath):
                print(f"  [extract] SKIPPED (AI-generated marker): {fpath}")
                state[chash] = {"file": fpath, "status": "skipped_ai", "ts": datetime.now().isoformat()}
                continue

            hits = extract_from_file(fpath)
            record = {
                "file": fpath,
                "content_hash": chash,
                "principles_detected": hits,
                "timestamp": datetime.now().isoformat(),
                "status": "PENDING_HUMAN_REVIEW"
            }
            results.append(record)
            state[chash] = {"file": fpath, "status": "extracted", "ts": datetime.now().isoformat()}

    if results:
        existing = []
        if os.path.exists(OUTPUT):
            try:
                existing = json.load(open(OUTPUT))
            except Exception:
                existing = []
        existing.extend(results)
        json.dump(existing, open(OUTPUT, "w"), indent=2)
        print(f"[extract_principles] Extracted {len(results)} file(s). Review: {OUTPUT}")
    else:
        print("[extract_principles] No new files to extract.")

    save_state(state)

if __name__ == "__main__":
    main()
